# ============================================
# script.py.mako - Plantilla para generar migraciones
# ============================================
# Cuando ejecutas "alembic revision --autogenerate", Alembic usa
# esta plantilla para crear el archivo de migración.
# 
# Las variables con  son reemplazadas automáticamente:
# - message: El mensaje que pusiste en -m "mensaje"
# - revision: ID único de esta migración
# - down_revision: ID de la migración anterior
# - create_date: Fecha de creación

"""add_user_uuid_to_movements

Revision ID: 38b8de14694e
Revises: 291d5b194821
Create Date: 2026-08-23 18:28:42.558279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b8de14694e'
down_revision: Union[str, None] = '291d5b194821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica la migración (crea/modifica tablas)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('user_uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Deshace la migración (vuelve al estado anterior)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_movements', 'user_uuid')
    # ### end Alembic commands ###